# Generated by Django 5.0.3 on 2024-03-30 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_file', models.FileField(upload_to='config_files/')),
                ('user_associated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.FileField(upload_to='trip_logs/')),
                ('logger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='WebApp.logger')),
            ],
        ),
        migrations.AddField(
            model_name='logger',
            name='current_trip',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_logger', to='WebApp.trip'),
        ),
    ]
