# Generated by Django 5.0.3 on 2024-04-02 14:46

import WebApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_trip_end_date_trip_last_communication_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='last_communication_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='log',
            field=models.FileField(upload_to=WebApp.models.Trip.get_upload_path),
        ),
    ]
