# Generated by Django 5.0.3 on 2024-04-10 12:01

import WebApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_trip_bme_data_trip_data_logger_config_trip_gps_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logger',
            name='config_file',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='log',
        ),
        migrations.AddField(
            model_name='logger',
            name='battery_level',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='logger',
            name='device_log_path',
            field=models.FileField(blank=True, null=True, upload_to=WebApp.models.Logger.get_upload_path),
        ),
        migrations.AddField(
            model_name='logger',
            name='last_communication_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logger',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
