# Generated by Django 5.0.3 on 2024-04-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_logger_last_gps_location_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logger',
            name='last_gps_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
