# Generated by Django 5.0.3 on 2024-04-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0008_logger_last_gps_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='last_communication_timestamp',
        ),
        migrations.AlterField(
            model_name='logger',
            name='battery_level',
            field=models.FloatField(blank=True, default=100, null=True),
        ),
    ]
