# Generated by Django 5.0.3 on 2024-04-18 12:00

import WebApp.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0009_remove_trip_last_communication_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='data_logger_config',
        ),
        migrations.AddField(
            model_name='trip',
            name='psd_data',
            field=models.FileField(null=True, upload_to=WebApp.models.Trip.get_upload_path),
        ),
        migrations.AlterField(
            model_name='trip',
            name='name',
            field=models.CharField(default='Default Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
        migrations.CreateModel(
            name='TripConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accelerometer_scale', models.IntegerField(choices=[(2, '2g'), (4, '4g'), (8, '8g'), (16, '16g')], default=8)),
                ('sample_rate', models.IntegerField(default=200)),
                ('impact_threshold', models.FloatField(default=4.0)),
                ('n_vibration_per_sample', models.IntegerField(default=512)),
                ('vibration_magnitude_threshold', models.FloatField(default=0.005)),
                ('vibration_interval_timer', models.IntegerField(default=20000)),
                ('bme_interval_timer', models.IntegerField(default=60000)),
                ('interval_bme_recording', models.IntegerField(default=2)),
                ('mqtt_interval_timer', models.IntegerField(default=300000)),
                ('gps_interval_timer', models.IntegerField(default=120000)),
                ('max_time_try_location', models.IntegerField(default=60)),
                ('esp_stats_interval_timer', models.IntegerField(default=120000)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='associated_config', to='WebApp.trip')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='config',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated_trip', to='WebApp.tripconfig'),
        ),
    ]
